// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartPayEngine.Infrastructure.Persistence;

#nullable disable

namespace SmartPayEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartPayDbContext))]
    partial class SmartPayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SmartPayEngine.Core.Entities.ReversalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AIExplanation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceNeeded")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedAmount")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessProbability")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionId");

                    b.ToTable("reversal_requests", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
