/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SendRouteImport } from './routes/send'
import { Route as ReversalsRouteImport } from './routes/reversals'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LedgerIntegrityRouteImport } from './routes/ledger-integrity'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HiveRouteImport } from './routes/hive'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ConvertRouteImport } from './routes/convert'
import { Route as BrandPreviewRouteImport } from './routes/brand-preview'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AddFundsRouteImport } from './routes/add-funds'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantIndexRouteImport } from './routes/assistant.index'
import { Route as ITokenRouteImport } from './routes/i.$token'
import { Route as BlogIntelligentPaymentRoutingGuideRouteImport } from './routes/blog.intelligent-payment-routing-guide'
import { Route as AssistantThreadIdRouteImport } from './routes/assistant.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ReversalsRoute = ReversalsRouteImport.update({
  id: '/reversals',
  path: '/reversals',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerIntegrityRoute = LedgerIntegrityRouteImport.update({
  id: '/ledger-integrity',
  path: '/ledger-integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HiveRoute = HiveRouteImport.update({
  id: '/hive',
  path: '/hive',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertRoute = ConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandPreviewRoute = BrandPreviewRouteImport.update({
  id: '/brand-preview',
  path: '/brand-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AddFundsRoute = AddFundsRouteImport.update({
  id: '/add-funds',
  path: '/add-funds',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantIndexRoute = AssistantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssistantRoute,
} as any)
const ITokenRoute = ITokenRouteImport.update({
  id: '/i/$token',
  path: '/i/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIntelligentPaymentRoutingGuideRoute =
  BlogIntelligentPaymentRoutingGuideRouteImport.update({
    id: '/blog/intelligent-payment-routing-guide',
    path: '/blog/intelligent-payment-routing-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssistantThreadIdRoute = AssistantThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AssistantRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-funds': typeof AddFundsRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/auth': typeof AuthRoute
  '/brand-preview': typeof BrandPreviewRoute
  '/convert': typeof ConvertRoute
  '/cookies': typeof CookiesRoute
  '/hive': typeof HiveRoute
  '/insights': typeof InsightsRoute
  '/invoices': typeof InvoicesRoute
  '/ledger-integrity': typeof LedgerIntegrityRoute
  '/privacy': typeof PrivacyRoute
  '/reversals': typeof ReversalsRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/transactions': typeof TransactionsRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/blog/intelligent-payment-routing-guide': typeof BlogIntelligentPaymentRoutingGuideRoute
  '/i/$token': typeof ITokenRoute
  '/assistant/': typeof AssistantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-funds': typeof AddFundsRoute
  '/auth': typeof AuthRoute
  '/brand-preview': typeof BrandPreviewRoute
  '/convert': typeof ConvertRoute
  '/cookies': typeof CookiesRoute
  '/hive': typeof HiveRoute
  '/insights': typeof InsightsRoute
  '/invoices': typeof InvoicesRoute
  '/ledger-integrity': typeof LedgerIntegrityRoute
  '/privacy': typeof PrivacyRoute
  '/reversals': typeof ReversalsRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/transactions': typeof TransactionsRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/blog/intelligent-payment-routing-guide': typeof BlogIntelligentPaymentRoutingGuideRoute
  '/i/$token': typeof ITokenRoute
  '/assistant': typeof AssistantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-funds': typeof AddFundsRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/auth': typeof AuthRoute
  '/brand-preview': typeof BrandPreviewRoute
  '/convert': typeof ConvertRoute
  '/cookies': typeof CookiesRoute
  '/hive': typeof HiveRoute
  '/insights': typeof InsightsRoute
  '/invoices': typeof InvoicesRoute
  '/ledger-integrity': typeof LedgerIntegrityRoute
  '/privacy': typeof PrivacyRoute
  '/reversals': typeof ReversalsRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/transactions': typeof TransactionsRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/blog/intelligent-payment-routing-guide': typeof BlogIntelligentPaymentRoutingGuideRoute
  '/i/$token': typeof ITokenRoute
  '/assistant/': typeof AssistantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-funds'
    | '/assistant'
    | '/auth'
    | '/brand-preview'
    | '/convert'
    | '/cookies'
    | '/hive'
    | '/insights'
    | '/invoices'
    | '/ledger-integrity'
    | '/privacy'
    | '/reversals'
    | '/send'
    | '/settings'
    | '/sitemap.xml'
    | '/team'
    | '/transactions'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/blog/intelligent-payment-routing-guide'
    | '/i/$token'
    | '/assistant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-funds'
    | '/auth'
    | '/brand-preview'
    | '/convert'
    | '/cookies'
    | '/hive'
    | '/insights'
    | '/invoices'
    | '/ledger-integrity'
    | '/privacy'
    | '/reversals'
    | '/send'
    | '/settings'
    | '/sitemap.xml'
    | '/team'
    | '/transactions'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/blog/intelligent-payment-routing-guide'
    | '/i/$token'
    | '/assistant'
  id:
    | '__root__'
    | '/'
    | '/add-funds'
    | '/assistant'
    | '/auth'
    | '/brand-preview'
    | '/convert'
    | '/cookies'
    | '/hive'
    | '/insights'
    | '/invoices'
    | '/ledger-integrity'
    | '/privacy'
    | '/reversals'
    | '/send'
    | '/settings'
    | '/sitemap.xml'
    | '/team'
    | '/transactions'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/blog/intelligent-payment-routing-guide'
    | '/i/$token'
    | '/assistant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddFundsRoute: typeof AddFundsRoute
  AssistantRoute: typeof AssistantRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrandPreviewRoute: typeof BrandPreviewRoute
  ConvertRoute: typeof ConvertRoute
  CookiesRoute: typeof CookiesRoute
  HiveRoute: typeof HiveRoute
  InsightsRoute: typeof InsightsRoute
  InvoicesRoute: typeof InvoicesRoute
  LedgerIntegrityRoute: typeof LedgerIntegrityRoute
  PrivacyRoute: typeof PrivacyRoute
  ReversalsRoute: typeof ReversalsRoute
  SendRoute: typeof SendRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiChatRoute: typeof ApiChatRoute
  BlogIntelligentPaymentRoutingGuideRoute: typeof BlogIntelligentPaymentRoutingGuideRoute
  ITokenRoute: typeof ITokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reversals': {
      id: '/reversals'
      path: '/reversals'
      fullPath: '/reversals'
      preLoaderRoute: typeof ReversalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger-integrity': {
      id: '/ledger-integrity'
      path: '/ledger-integrity'
      fullPath: '/ledger-integrity'
      preLoaderRoute: typeof LedgerIntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hive': {
      id: '/hive'
      path: '/hive'
      fullPath: '/hive'
      preLoaderRoute: typeof HiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-preview': {
      id: '/brand-preview'
      path: '/brand-preview'
      fullPath: '/brand-preview'
      preLoaderRoute: typeof BrandPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-funds': {
      id: '/add-funds'
      path: '/add-funds'
      fullPath: '/add-funds'
      preLoaderRoute: typeof AddFundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/': {
      id: '/assistant/'
      path: '/'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AssistantIndexRouteImport
      parentRoute: typeof AssistantRoute
    }
    '/i/$token': {
      id: '/i/$token'
      path: '/i/$token'
      fullPath: '/i/$token'
      preLoaderRoute: typeof ITokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/intelligent-payment-routing-guide': {
      id: '/blog/intelligent-payment-routing-guide'
      path: '/blog/intelligent-payment-routing-guide'
      fullPath: '/blog/intelligent-payment-routing-guide'
      preLoaderRoute: typeof BlogIntelligentPaymentRoutingGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/$threadId': {
      id: '/assistant/$threadId'
      path: '/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AssistantThreadIdRouteImport
      parentRoute: typeof AssistantRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AssistantRouteChildren {
  AssistantThreadIdRoute: typeof AssistantThreadIdRoute
  AssistantIndexRoute: typeof AssistantIndexRoute
}

const AssistantRouteChildren: AssistantRouteChildren = {
  AssistantThreadIdRoute: AssistantThreadIdRoute,
  AssistantIndexRoute: AssistantIndexRoute,
}

const AssistantRouteWithChildren = AssistantRoute._addFileChildren(
  AssistantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddFundsRoute: AddFundsRoute,
  AssistantRoute: AssistantRouteWithChildren,
  AuthRoute: AuthRoute,
  BrandPreviewRoute: BrandPreviewRoute,
  ConvertRoute: ConvertRoute,
  CookiesRoute: CookiesRoute,
  HiveRoute: HiveRoute,
  InsightsRoute: InsightsRoute,
  InvoicesRoute: InvoicesRoute,
  LedgerIntegrityRoute: LedgerIntegrityRoute,
  PrivacyRoute: PrivacyRoute,
  ReversalsRoute: ReversalsRoute,
  SendRoute: SendRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  TransactionsRoute: TransactionsRoute,
  ApiChatRoute: ApiChatRoute,
  BlogIntelligentPaymentRoutingGuideRoute:
    BlogIntelligentPaymentRoutingGuideRoute,
  ITokenRoute: ITokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
